  builds:
    - id: arvan_linux
      env:
      - CGO_ENABLED=0    
      main: ./cmd/arvan/arvan.go
      binary: arvan
      goos:
        - linux
      goarch:
        - amd64
      ldflags:
        - -s -w
        - -X 'k8s.io/client-go/pkg/version.gitVersion=v{{.Version}}'
        - -X 'k8s.io/client-go/pkg/version.gitCommit={{.Commit}}'
        - -X 'github.com/openshift/oc/pkg/version.versionFromGit=v{{.Version}}'
        - -X 'github.com/openshift/oc/pkg/version.commitFromGit={{.Commit}}'
      hooks:
        post:
          - upx -7 "{{ .Path }}"
    - id: arvan_windows
      env:
      - CGO_ENABLED=1    
      main: ./cmd/arvan/arvan.go
      binary: arvan
      goos:
        - windows
      goarch:
        - amd64
      ldflags:
        - -s -w
        - -X 'k8s.io/client-go/pkg/version.gitVersion=v{{.Version}}'
        - -X 'k8s.io/client-go/pkg/version.gitCommit={{.Commit}}'
        - -X 'github.com/openshift/oc/pkg/version.versionFromGit=v{{.Version}}'
        - -X 'github.com/openshift/oc/pkg/version.commitFromGit={{.Commit}}'
      hooks:
        post:
          - upx -7 "{{ .Path }}"
    - id: arvan_darwin  
      main: ./cmd/arvan/arvan.go
      binary: arvan
      goos:
        - darwin
      goarch:
        - amd64
      ldflags:
        - -s -w
        - -X 'k8s.io/client-go/pkg/version.gitVersion=v{{.Version}}'
        - -X 'k8s.io/client-go/pkg/version.gitCommit={{.Commit}}'
        - -X 'github.com/openshift/oc/pkg/version.versionFromGit=v{{.Version}}'
        - -X 'github.com/openshift/oc/pkg/version.commitFromGit={{.Commit}}'
      hooks:
        post:
          - upx -7 "{{ .Path }}"
  archives:
    -
      format_overrides:
        - goos: windows
          format: zip
      files:
        - none*
      name_template: 'arvan_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
        }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
